# Generated by Django 6.1 on 2026-08-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsetting',
            name='timezone',
            field=models.CharField(default='UTC', max_length=255),
        ),
    ]
