# Generated by Django 6.1 on 2026-08-07 21:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicGroupPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='clinics.clinic')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_permissions', to='auth.group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'verbose_name': 'clinic group permission',
                'verbose_name_plural': 'clinic group permissions',
                'db_table': 'clinic_group_permissions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'group', 'permission'), name='clinic_group_permission_unique')],
            },
        ),
        migrations.CreateModel(
            name='ClinicUserGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='clinics.clinic')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_users', to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'clinic user group',
                'verbose_name_plural': 'clinic user groups',
                'db_table': 'clinic_user_groups',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'user', 'group'), name='clinic_user_groups_unique')],
            },
        ),
        migrations.CreateModel(
            name='ClinicUserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='clinics.clinic')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_users', to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'clinic user permission',
                'verbose_name_plural': 'clinic user permissions',
                'db_table': 'clinic_user_permissions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'user', 'permission'), name='clinic_user_permissions_unique')],
            },
        ),
    ]
