# Generated by Django 6.1 on 2026-08-07 22:20

from django.db import migrations

def seed_groups(apps, _):
    Group = apps.get_model('auth', 'Group')

    groups_to_upsert = [
        Group(name='Owner'),
        Group(name='Admin'),
        Group(name='Practitioner'),
        Group(name='Receptionist'),
        Group(name='Inventory Staff'),
        Group(name='Guest'),
    ]

    Group.objects.bulk_create(
        groups_to_upsert,
        update_conflicts=True,
        unique_fields=['name'],
        update_fields=['name']
    )

def reverse_seed_groups(apps, _):
    Group = apps.get_model('auth', 'Group')

    Group.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
        ('auth', '__first__')
    ]

    operations = [
        migrations.RunPython(
            seed_groups,
            reverse_seed_groups,
        ),
    ]
