# Generated by Django 6.1 on 2026-08-07 21:26

import csv
from pathlib import Path
from django.core.management.color import no_style
from django.db import migrations


def seed_locations(apps, schema_editor):

    Country = apps.get_model("locations", "Country")
    State = apps.get_model("locations", "State")

    connection = schema_editor.connection

    app_dir = Path(__file__).resolve().parents[1]

    countries_file = app_dir / "seeds" / "countries.csv"
    states_file = app_dir / "seeds" / "states.csv"

    # Cteate countries from data in csv file
    with countries_file.open(mode="r", encoding="utf-8-sig", newline="") as file:

        reader = csv.DictReader(file)

        for row in reader:
            country_id = int(row["id"])

            Country.objects.update_or_create(
                id=country_id,
                defaults={
                    "name": row["name"],
                }
            )

    # Creat states from data in the csv file
    with states_file.open(mode="r", encoding="utf-8-sig", newline="") as file:
        reader = csv.DictReader(file)

        for row in reader:
            state_id = int(row["id"])

            State.objects.update_or_create(
                id=state_id,
                defaults={
                    "name": row["name"],
                    "country_id": int(row["country_id"]),
                },
            )

    # Reset Postgresql sequence
    sequence_sql = connection.ops.sequence_reset_sql(
        no_style(),
        [Country, State],
    )

    with connection.cursor() as cursor:
        for sql in sequence_sql:
            cursor.execute(sql)

def reverse_seed_locations(apps, schema_editor):
    State = apps.get_model("locations", "State")
    Country = apps.get_model("locations", "Country")

    State.objects.all().delete()
    Country.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            seed_locations,
            reverse_seed_locations,
        ),
    ]
